spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: welcome-api
          uri: lb://WELCOME-API
          predicates:
            - Path=/welcome
          # filters:
          #   - JwtAuthenticationFilter
          metadata:
            cors:
              allowedOrigins: '*'
              allowedHeaders: '*'
              maxAge: 30

        - id: greet-api
          uri: lb://GREET-API
          predicates:
            - Path=/greet
          # filters:
          #   - name: JwtAuthenticationFilter
          metadata:
            cors:
              allowedOrigins: '*'
              allowedHeaders: '*'
              maxAge: 30

        - id: authentication-api
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/api/user/**
          # filters:
          #   - JwtAuthenticationFilter
          metadata:
            cors:
              allowedOrigins: '*'
              allowedHeaders: '*'
              maxAge: 30
jwt:
 secretKey: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9eyJzdWIiOiJzaXJpIiwibmFtZSI6Im1hbGxpIiwiaWF0IjoxNTE2MjM5MDIyfQ8jFhj-d5J2hWOUm76Wf0M6sp1OFattmR68DO8vbkrDth0qPmkTTOtaEtuCvv7cgQ-VUGbBjAilxALFP5rzjt4w
 expirationTime: 60000
