server:
  port: 8080

spring:
  redis:
    host: localhost            # Redis server host
    port: 6379                 # Redis server port
    # password: yourPassword     # (Optional) Password if your Redis is secured
    # timeout: 2000              # Connection timeout in milliseconds
    lettuce:
      pool:
        max-active: 8          # Max active connections
        max-idle: 8            # Max idle connections
        min-idle: 0            # Min idle connections

  cache:
    redis:
      time-to-live: 300000      # Default TTL for cache entries in milliseconds
      cache-null-values: false   # Don't cache null values

  security:
    user:
      name: admin
      password: admin

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bigil
    username: root
    password: 142169

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  app:
    jwtSecretKey: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9eyJzdWIiOiJzaXJpIiwibmFtZSI6Im1hbGxpIiwiaWF0IjoxNTE2MjM5MDIyfQ8jFhj-d5J2hWOUm76Wf0M6sp1OFattmR68DO8vbkrDth0qPmkTTOtaEtuCvv7cgQ-VUGbBjAilxALFP5rzjt4w
    jwtExpirationMs: 60000

  boot:
    admin:
      client:
        url: http://localhost:1111/

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.security: DEBUG
    hibernate:
      sql: DEBUG
    com.example.securitydemo: DEBUG
