server:
 port: 8080
 
spring:
  security:
    user:
      name: admin
      password: admin
  datasource:
    driver-class-name: org.h2.Driver
    password: siri
    url: jdbc:h2:mem:test
    username: siri
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  app:
    jwtSecretKey: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9eyJzdWIiOiJzaXJpIiwibmFtZSI6Im1hbGxpIiwiaWF0IjoxNTE2MjM5MDIyfQ8jFhj-d5J2hWOUm76Wf0M6sp1OFattmR68DO8vbkrDth0qPmkTTOtaEtuCvv7cgQ-VUGbBjAilxALFP5rzjt4w
    jwtExpirationMs: 60000
   boot: 
     admin:
      client:
        url: http://localhost:1111/
      
# Eureka server not run 8761 port then using below property to register APIs, Otherwise not declare
# Below Property is Optional
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
# Actuator All EndPoint
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        sql: DEBUG
    com:
      example:
        securitydemo: DEBUG
