server:
  port: 8080

spring:
  security:
    user:
      name: admin
      password: admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bigil
    password: root
    username: 142169
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  app:
    jwtSecretKey: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9eyJzdWIiOiJzaXJpIiwibmFtZSI6Im1hbGxpIiwiaWF0IjoxNTE2MjM5MDIyfQ8jFhj-d5J2hWOUm76Wf0M6sp1OFattmR68DO8vbkrDth0qPmkTTOtaEtuCvv7cgQ-VUGbBjAilxALFP5rzjt4w
    jwtExpirationMs: 60000
  boot:
    admin:
      client:
        url: http://localhost:1111/

# Eureka server not running on port 8761, use below property to register APIs, otherwise not declare.
# The below property is optional
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/

# Actuator All Endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        sql: DEBUG
    com:
      example:
        securitydemo: DEBUG
